# ============================================================================
# NAMESPACE
# ============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: ejemplo-06
  labels:
    ejemplo: probes-resources
