# ============================================================================
# NAMESPACE
# ============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: ejemplo-05
  labels:
    ejemplo: storage
